import type { ErrorRequestHandler, RequestHandler } from 'express'
import type { PostgrestError } from '@supabase/supabase-js'
import { ZodError } from 'zod'

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

export function fromDatabaseError(error: PostgrestError): ApiError {
  if (error.code === 'PGRST116') return new ApiError(404, 'not_found', 'Resource not found.')
  if (error.code === 'P0002') return new ApiError(404, 'not_found', error.message)
  if (error.code === 'P4090') return new ApiError(409, 'stale_appointment', error.message)
  if (error.code === 'P4091') return new ApiError(409, 'employment_has_active_bookings', error.message)
  if (error.code === 'P4092') return new ApiError(409, 'employment_not_active', error.message)
  if (error.code === 'P4093') return new ApiError(409, 'rehire_requires_owner_approval', error.message)
  if (error.code === 'P4094') return new ApiError(409, 'already_employed', error.message)
  if (error.code === 'P4095') return new ApiError(409, 'stale_verification', error.message)
  if (error.code === 'P4096') return new ApiError(409, 'idempotency_conflict', error.message)
  if (error.code === 'P4097') return new ApiError(409, 'verification_locked', error.message)
  if (error.code === 'P4098') return new ApiError(409, 'evidence_processing', error.message)
  if (error.code === 'P4099') return new ApiError(409, 'cooldown_active', error.message)
  if (error.code === 'P4031') return new ApiError(403, 'capability_required', error.message)
  if (error.code === 'P4020') return new ApiError(409, 'conflict', error.message)
  // P4021 is a precondition, not a stale read, and the two need different codes
  // because the client's reaction to them is opposite. `conflict` means "reload
  // and try again"; this means "something is missing, and reloading will not
  // change that". Sharing one code made Shop Setup answer a publish blocked by
  // an unpublishable shop with "we reloaded the latest version", which is both
  // wrong and an infinite loop for the owner. Found in browser smoke, 2026-07-30.
  if (error.code === 'P4021') return new ApiError(409, 'precondition_failed', error.message)
  if (error.code === 'P4022') return new ApiError(409, 'media_limit', error.message)
  if (error.code === 'P4023') return new ApiError(409, 'request_already_resolved', error.message)
  if (error.code === 'P4024') return new ApiError(409, 'hiring_full', error.message)
  if (error.code === 'P4025') return new ApiError(409, 'schedule_has_active_bookings', error.message)
  // P2-07 availability engine. Each one names a specific reason a slot is not
  // bookable, so the customer sees why instead of a generic conflict.
  if (error.code === 'P4026') return new ApiError(409, 'chairs_unavailable', error.message)
  if (error.code === 'P4027') return new ApiError(409, 'shop_not_bookable', error.message)
  if (error.code === 'P4028') return new ApiError(409, 'outside_shop_hours', error.message)
  if (error.code === 'P4029') return new ApiError(409, 'outside_booking_window', error.message)
  if (error.code === 'P4030') return new ApiError(409, 'provider_not_qualified', error.message)
  if (error.code === 'P4033') return new ApiError(409, 'no_provider_available', error.message)
  // P4-03 trust. Both are preconditions rather than stale reads, and they get
  // their own codes because a closed edit window and an ineligible visit call for
  // different sentences: one is "you are too late", the other is "this visit
  // never unlocked a review".
  if (error.code === 'P4034') return new ApiError(409, 'rating_window_closed', error.message)
  if (error.code === 'P4035') return new ApiError(409, 'rating_not_eligible', error.message)
  // P4-01 messaging. A block is a deliberate user choice, not a server fault, and
  // a send limit is a 429 so a client can back off rather than retry immediately.
  if (error.code === 'P4036') return new ApiError(403, 'messages_blocked', error.message)
  if (error.code === 'P4037') return new ApiError(429, 'rate_limited', error.message)
  if (error.code === 'P4041') return new ApiError(404, 'invalid_code', error.message)
  if (error.code === '23505') return new ApiError(409, 'conflict', 'That record already exists.')
  if (error.code === '23P01') return new ApiError(409, 'slot_taken', 'That appointment slot is already taken.')
  // `22023` is this codebase's convention for a deliberate `raise exception`, so
  // its message is product copy and is forwarded. The other three are usually
  // generated by Postgres and name constraints and columns
  // (`violates check constraint "appointments_notes_length"`), which is internal
  // detail a client has no use for. A deliberate message under those codes is
  // still forwarded; only the generated shapes are replaced.
  if (error.code === '22023') return new ApiError(400, 'validation', error.message)
  if (error.code === '23503' || error.code === '23514' || error.code === '22P02') {
    return new ApiError(400, 'validation', isGeneratedPostgresMessage(error.message)
      ? 'That request contains a value this action will not accept.'
      : error.message)
  }
  if (error.code === '42501') return new ApiError(403, 'forbidden', 'You are not allowed to perform this action.')
  return new ApiError(500, 'database_error', 'The database request failed.')
}

/**
 * Recognises the messages Postgres writes itself, as opposed to the ones a
 * `raise exception ... message = '...'` in a command deliberately wrote.
 */
function isGeneratedPostgresMessage(message: string): boolean {
  return /violates (foreign key|check|not-null) constraint/i.test(message)
    || /invalid input syntax for( type)?/i.test(message)
    || /new row for relation/i.test(message)
    || /value too long for type/i.test(message)
}

export function requireData<T>(data: T | null, error: PostgrestError | null): T {
  if (error) throw fromDatabaseError(error)
  if (data === null) throw new ApiError(404, 'not_found', 'Resource not found.')
  return data
}

export const notFoundHandler: RequestHandler = (request, _response, next) => {
  next(new ApiError(404, 'route_not_found', `No route for ${request.method} ${request.originalUrl}.`))
}

export const errorHandler: ErrorRequestHandler = (error: unknown, _request, response, _next) => {
  if (typeof error === 'object' && error !== null
    && 'type' in error && error.type === 'entity.parse.failed') {
    response.status(400).json({
      error: { code: 'invalid_json', message: 'Request body contains invalid JSON.' },
    })
    return
  }

  if (error instanceof ZodError) {
    response.status(400).json({
      error: {
        code: 'validation',
        message: 'Request validation failed.',
        details: error.issues,
      },
    })
    return
  }

  if (error instanceof ApiError) {
    response.status(error.status).json({
      error: {
        code: error.code,
        message: error.message,
        ...(error.details === undefined ? {} : { details: error.details }),
      },
    })
    return
  }

  const message = error instanceof Error ? error.message : 'Unknown error'
  if (process.env.NODE_ENV !== 'test') console.error(error)
  response.status(500).json({
    error: {
      code: 'internal_error',
      message: 'An unexpected server error occurred.',
      ...(process.env.NODE_ENV === 'development' ? { details: message } : {}),
    },
  })
}
